extends:
  - '@meyfa/eslint-config'
  - 'plugin:jsdoc/recommended'

parserOptions:
  project: './tsconfig.lint.json'

rules:
  # require JSDoc on every standard location, and also on classes, interfaces and enums
  jsdoc/require-jsdoc: ['error', { contexts: ['ClassDeclaration', 'TSInterfaceDeclaration', 'TSEnumDeclaration'] }]
  jsdoc/require-param-type: off
  jsdoc/require-returns-type: off
  jsdoc/no-types: error
