extends:
  - 'standard-with-typescript'
  - 'plugin:jsdoc/recommended'

parserOptions:
  project: './tsconfig.eslint.json'

overrides:
  - files: '*.test.js'
    env:
      mocha: true
    rules:
      no-unused-expressions: off
